/**
 * Human Spotlight — daily positive human interest on the homepage.
 * Generated by the human-spotlight agent (Grok + web_search); stored in AGENTS KV.
 */

export interface HumanSpotlightSource {
  title: string;
  url: string;
}

export interface HumanSpotlightPerson {
  name: string;
  /** Short achievement headline. */
  achievement: string;
  /** Full article body (paragraphs separated by \n\n). */
  article: string;
  /** Optional one-line "why this person today". */
  whyNow?: string;
  location?: string;
  /** Domain: science, community, arts, health, environment, sports, etc. */
  field?: string;
  /** Wikimedia Commons thumbnail only. */
  imageUrl?: string | null;
  /** Optional YouTube video id (11 chars) for an embedded explainer. */
  videoId?: string | null;
  sources?: HumanSpotlightSource[];
}

export interface HumanSpotlightPayload {
  /** YYYY-MM-DD in America/New_York — one person per desk day. */
  dateKey: string;
  dateLabel: string;
  generatedAt: string;
  person: HumanSpotlightPerson;
  /** Last ~21 names chosen (for agent skip-list). */
  recentNames?: string[];
}

/** Full calendar day key (ET) so the spotlight rolls daily. */
export function spotlightDateKey(now = new Date()): string {
  try {
    const parts = new Intl.DateTimeFormat("en-CA", {
      timeZone: "America/New_York",
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
    }).formatToParts(now);
    const y = parts.find((p) => p.type === "year")?.value;
    const m = parts.find((p) => p.type === "month")?.value;
    const d = parts.find((p) => p.type === "day")?.value;
    if (y && m && d) return `${y}-${m}-${d}`;
  } catch {
    /* fall through */
  }
  return now.toISOString().slice(0, 10);
}

export function spotlightDateLabel(now = new Date()): string {
  try {
    return new Intl.DateTimeFormat("en-US", {
      timeZone: "America/New_York",
      month: "long",
      day: "numeric",
      year: "numeric",
    }).format(now);
  } catch {
    return spotlightDateKey(now);
  }
}

function safeHttpUrl(raw: unknown): string | null {
  const u = String(raw ?? "").trim().slice(0, 500);
  if (!/^https:\/\//i.test(u)) return null;
  try {
    const parsed = new URL(u);
    if (parsed.protocol !== "https:") return null;
    return parsed.href;
  } catch {
    return null;
  }
}

export function normalizeSpotlightPerson(raw: unknown): HumanSpotlightPerson | null {
  if (!raw || typeof raw !== "object") return null;
  const r = raw as Record<string, unknown>;
  const name = String(r.name || "").trim().slice(0, 80);
  const achievement = String(r.achievement || "").trim().slice(0, 160);
  let article = String(r.article || "").trim().slice(0, 4000);
  if (!name || !achievement || article.length < 80) return null;
  // Normalize paragraphs
  article = article
    .replace(/\r\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  let imageUrl: string | null = null;
  if (r.imageUrl) {
    const u = String(r.imageUrl).trim();
    if (u.startsWith("https://upload.wikimedia.org/wikipedia/commons/")) {
      imageUrl = u.slice(0, 500);
    }
  }

  let videoId: string | null = null;
  if (r.videoId) {
    const v = String(r.videoId).trim();
    if (/^[\w-]{11}$/.test(v)) videoId = v;
  }

  const sources = (Array.isArray(r.sources) ? r.sources : [])
    .map((s) => {
      if (!s || typeof s !== "object") return null;
      const o = s as Record<string, unknown>;
      const title = String(o.title || "").trim().slice(0, 120);
      const url = safeHttpUrl(o.url);
      if (!title || !url) return null;
      return { title, url };
    })
    .filter((x): x is HumanSpotlightSource => x != null)
    .slice(0, 6);

  return {
    name,
    achievement,
    article,
    whyNow: String(r.whyNow || "").trim().slice(0, 200) || undefined,
    location: String(r.location || "").trim().slice(0, 80) || undefined,
    field: String(r.field || "").trim().slice(0, 40) || undefined,
    imageUrl,
    videoId,
    sources: sources.length ? sources : undefined,
  };
}

export function normalizeSpotlightPayload(raw: unknown): HumanSpotlightPayload | null {
  if (!raw || typeof raw !== "object") return null;
  const r = raw as Record<string, unknown>;
  const dateKey = String(r.dateKey || "").trim();
  if (!/^\d{4}-\d{2}-\d{2}$/.test(dateKey)) return null;
  const person = normalizeSpotlightPerson(r.person);
  if (!person) return null;
  const recentNames = (Array.isArray(r.recentNames) ? r.recentNames : [])
    .map((n) => String(n || "").trim().slice(0, 80))
    .filter(Boolean)
    .slice(0, 30);
  return {
    dateKey,
    dateLabel: String(r.dateLabel || dateKey).slice(0, 48),
    generatedAt: String(r.generatedAt || new Date().toISOString()).slice(0, 40),
    person,
    recentNames: recentNames.length ? recentNames : undefined,
  };
}

/** First ~n chars of article for homepage teaser (word-boundary). */
export function teaserFromArticle(article: string, max = 200): string {
  const plain = String(article || "")
    .replace(/\s+/g, " ")
    .trim();
  if (plain.length <= max) return plain;
  const cut = plain.slice(0, max - 1);
  const sp = cut.lastIndexOf(" ");
  return (sp > max - 40 ? cut.slice(0, sp) : cut).trimEnd() + "…";
}

export function personInitials(name: string): string {
  const parts = String(name || "")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  if (!parts.length) return "?";
  if (parts.length === 1) return parts[0]!.slice(0, 2).toUpperCase();
  return (parts[0]![0]! + parts[parts.length - 1]![0]!).toUpperCase();
}
