/**
 * Portrait URLs for politician cards (Wikimedia Commons via Wikipedia REST).
 * Regenerated from en.wikipedia.org page summaries. Hotlink is allowed for
 * Wikimedia content with attribution; we credit Wikipedia on the profile.
 * Missing slugs fall back to monogram avatars in the UI.
 */
export const POLITICIAN_PHOTOS: Record<string, string> = {
  "mike-collins": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Rep._Mike_Collins_official_photo%2C_118th_Congress.jpg/440px-Rep._Mike_Collins_official_photo%2C_118th_Congress.jpg",
  "jon-ossoff": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Jon_Ossoff_Senate_Portrait_2021.jpg/440px-Jon_Ossoff_Senate_Portrait_2021.jpg",
  "roy-cooper": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Roy_Cooper_in_November_2023_%28cropped2%29.jpg/440px-Roy_Cooper_in_November_2023_%28cropped2%29.jpg",
  "michael-whatley": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Michael_Whatley_%2854670563614%29_%28cropped%29.jpg/440px-Michael_Whatley_%2854670563614%29_%28cropped%29.jpg",
  "susan-collins": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Senator_Susan_Collins_2014_official_portrait.jpg/440px-Senator_Susan_Collins_2014_official_portrait.jpg",
  "thom-tillis": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Sen._Thom_Tillis_%28R-NC%29%2C_Official_Portrait%2C_117th_Congress_%28cropped%29.jpg/440px-Sen._Thom_Tillis_%28R-NC%29%2C_Official_Portrait%2C_117th_Congress_%28cropped%29.jpg",
  "graham-platner": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Platner_headshot.jpg/440px-Platner_headshot.jpg",
  "james-talarico": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/James_Talarico_Press_Conference_%28cropped%29.jpg/440px-James_Talarico_Press_Conference_%28cropped%29.jpg",
  "colin-allred": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Colin_Allred%2C_official_portrait%2C_117th_Congress.jpg/440px-Colin_Allred%2C_official_portrait%2C_117th_Congress.jpg",
  "ken-paxton": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/K_Paxton.jpg/440px-K_Paxton.jpg",
  "john-cornyn": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/John_Cornyn.jpg/440px-John_Cornyn.jpg",
  "tina-smith": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Sen._Tina_Smith_%28D-MN%29%2C_Official_Portrait%2C_116th_Congress.jpg/440px-Sen._Tina_Smith_%28D-MN%29%2C_Official_Portrait%2C_116th_Congress.jpg",
  "angie-craig": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Angie_Craig%2C_official_portrait_%28119th_Congress%29.jpg/440px-Angie_Craig%2C_official_portrait_%28119th_Congress%29.jpg",
  "scott-brown": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Ambassador_Scott_Brown.jpg/440px-Ambassador_Scott_Brown.jpg",
  "jeanne-shaheen": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Sen._Jeanne_Shaheen_%28D-NH%29%2C_Official_Portrait%2C_117th_Congress.jpg/440px-Sen._Jeanne_Shaheen_%28D-NH%29%2C_Official_Portrait%2C_117th_Congress.jpg",
  "john-sununu": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/John_E._Sununu.jpg/440px-John_E._Sununu.jpg",
  "peggy-flanagan": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/2026PeggyFlanagan_%28newcropped%29.jpg/440px-2026PeggyFlanagan_%28newcropped%29.jpg",
  "chris-pappas": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Chris_Pappas%2C_official_portrait%2C_116th_Congress.jpg/440px-Chris_Pappas%2C_official_portrait%2C_116th_Congress.jpg",
  "haley-stevens": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Haley_Stevens%2C_official_portrait%2C_116th_Congress.jpg/440px-Haley_Stevens%2C_official_portrait%2C_116th_Congress.jpg",
  "abdul-el-sayed": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Abdul_El-Sayed_meet-and-greet_by_Conlan_Houston_5_%28cropped%29.jpg/440px-Abdul_El-Sayed_meet-and-greet_by_Conlan_Houston_5_%28cropped%29.jpg",
  "dick-durbin": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Dick_Durbin_2022_official_portrait_%28cropped%29.jpg/440px-Dick_Durbin_2022_official_portrait_%28cropped%29.jpg",
  "steve-daines": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Steve_Daines%2C_Official_Portrait%2C_116th_Congress.jpg/440px-Steve_Daines%2C_Official_Portrait%2C_116th_Congress.jpg",
  "john-hickenlooper": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/John_Hickenlooper%2C_official_portrait%2C_117th_Congress.jpeg/440px-John_Hickenlooper%2C_official_portrait%2C_117th_Congress.jpeg",
  "gary-peters": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Gary_Peters_official_photo_115th_congress.jpg/440px-Gary_Peters_official_photo_115th_congress.jpg",
  "annie-andrews": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Annie_Andrews_Greenville_%28cropped%29.jpg/440px-Annie_Andrews_Greenville_%28cropped%29.jpg",
  "darline-graham-nordone": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Darline_Graham_Swearing_In.png/440px-Darline_Graham_Swearing_In.png",
  "mike-rogers": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Mike-Rogers-Head-Shot-2_%283x4_cropped%29.jpg/440px-Mike-Rogers-Head-Shot-2_%283x4_cropped%29.jpg",
  "pete-ricketts": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Sen._Pete_Ricketts_Official_Portrait%2C_118th_Congress.jpg/440px-Sen._Pete_Ricketts_Official_Portrait%2C_118th_Congress.jpg",
  "lindsey-graham": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/U.S._Senator_Lindsey_Graham%2C_Official_Photo%2C_113th_Congress_%283x4_cropped%29.jpg/440px-U.S._Senator_Lindsey_Graham%2C_Official_Photo%2C_113th_Congress_%283x4_cropped%29.jpg",
  "cory-booker": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Cory_Booker%2C_official_portrait_%28119th_Congress%29.jpg/440px-Cory_Booker%2C_official_portrait_%28119th_Congress%29.jpg",
  "ted-cruz": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Ted_Cruz_official_116th_portrait_%283x4_cropped%29.jpg/440px-Ted_Cruz_official_116th_portrait_%283x4_cropped%29.jpg",
  "raphael-warnock": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Raphael_Warnock_official_photo.jpg/440px-Raphael_Warnock_official_photo.jpg",
  "tammy-baldwin": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Tammy_Baldwin%2C_official_portrait%2C_113th_Congress.jpg/440px-Tammy_Baldwin%2C_official_portrait%2C_113th_Congress.jpg",
  "elissa-slotkin": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Elissa_Slotkin_2026_Official_Portrait_%28cropped%29.jpg/440px-Elissa_Slotkin_2026_Official_Portrait_%28cropped%29.jpg",
  "john-fetterman": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/John_Fetterman_official_portrait.jpg/440px-John_Fetterman_official_portrait.jpg",
  "michael-bennet": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Senator_Mike_Bennett.jpg/440px-Senator_Mike_Bennett.jpg",
  "ruben-gallego": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Senator_Ruben_Gallego_Official_Portrait.jpg/440px-Senator_Ruben_Gallego_Official_Portrait.jpg",
  "dave-mccormick": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/McCormick_Portrait_%28HR%29.jpg/440px-McCormick_Portrait_%28HR%29.jpg",
  "jacky-rosen": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Senator_Jacky_Rosen_Official_Portrait_%282022%29.jpg/440px-Senator_Jacky_Rosen_Official_Portrait_%282022%29.jpg",
  "mark-kelly": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Sen._Mark_Kelly_%28D-AZ%29%2C_Official_Portrait%2C_119th_Congress.jpg/440px-Sen._Mark_Kelly_%28D-AZ%29%2C_Official_Portrait%2C_119th_Congress.jpg",
  "sherrod-brown": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Sen._Sherrod_Brown_%28D-Ohio%29%2C_Official_Portrait%2C_117th_Congress.jpg/440px-Sen._Sherrod_Brown_%28D-Ohio%29%2C_Official_Portrait%2C_117th_Congress.jpg",
  "kari-lake": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Kari_Lake_by_Gage_Skidmore_4.jpg/440px-Kari_Lake_by_Gage_Skidmore_4.jpg",
  "bernie-moreno": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Sen._Bernie_Moreno_official_photo%2C_119th_Congress_%28HR%29.jpg/440px-Sen._Bernie_Moreno_official_photo%2C_119th_Congress_%28HR%29.jpg",
  "tim-sheehy": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Sen._Tim_Sheehy%2C_alternate_portrait%2C_119th_Congress.jpg/440px-Sen._Tim_Sheehy%2C_alternate_portrait%2C_119th_Congress.jpg",
  "eric-hovde": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/2024_United_States_Senate_election_in_Wisconsin_results_map_by_county.svg/440px-2024_United_States_Senate_election_in_Wisconsin_results_map_by_county.svg.png",
  "jon-husted": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Sen._Jon_Husted_official_portrait%2C_119th_Congress.jpg/440px-Sen._Jon_Husted_official_portrait%2C_119th_Congress.jpg",
  "jon-tester": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/JonTester.jpg/440px-JonTester.jpg",
  "larry-hogan": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Larry_Hogan_%282021%29_%28cropped%29.jpg/440px-Larry_Hogan_%282021%29_%28cropped%29.jpg",
  "joe-lombardo": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Joe_Lombardo_by_Gage_Skidmore_%283x4_cropped%29.jpg/440px-Joe_Lombardo_by_Gage_Skidmore_%283x4_cropped%29.jpg",
  "deb-fischer": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Deb_Fischer_118th_Congress.jpg/440px-Deb_Fischer_118th_Congress.jpg",
  "jim-banks": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Senator_Banks_Official_Portrait.jpg/440px-Senator_Banks_Official_Portrait.jpg",
  "angela-alsobrooks": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Sen._Angela_Alsobrooks_official_Senate_photo%2C_119th_Congress.jpg/440px-Sen._Angela_Alsobrooks_official_Senate_photo%2C_119th_Congress.jpg",
  "brian-kemp": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Brian_Kemp_portrait%2C_2024_%28cropped%29.jpg/440px-Brian_Kemp_portrait%2C_2024_%28cropped%29.jpg",
  "josh-shapiro": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Josh_Shapiro_December_2025.jpg/440px-Josh_Shapiro_December_2025.jpg",
  "gavin-newsom": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Governor_of_California_Gavin_Newsom_%28cropped_3x4%29.jpg/440px-Governor_of_California_Gavin_Newsom_%28cropped_3x4%29.jpg",
  "phil-weiser": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/AG_Phil_Weiser.jpg/440px-AG_Phil_Weiser.jpg",
  "gretchen-whitmer": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/2025_Gretchen_Whitmer_%28cropped%29.jpg/440px-2025_Gretchen_Whitmer_%28cropped%29.jpg",
  "greg-abbott": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Greg_Abbott_at_NASA_2024_%28cropped%29.jpg/440px-Greg_Abbott_at_NASA_2024_%28cropped%29.jpg",
  "katie-hobbs": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Katie_Hobbs_2026.jpg/440px-Katie_Hobbs_2026.jpg",
  "ron-desantis": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Ron_DeSantis_official_photo.jpg/440px-Ron_DeSantis_official_photo.jpg",
  "andy-beshear": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Andy_Beshear_in_April_2026_%28cropped%29.jpg/440px-Andy_Beshear_in_April_2026_%28cropped%29.jpg",
  "glenn-youngkin": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Youngkin_Governor_Portrait.jpg/440px-Youngkin_Governor_Portrait.jpg",
  "jb-pritzker": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Governor_JB_Pritzker_official_portrait_2019_%28crop%29.jpg/440px-Governor_JB_Pritzker_official_portrait_2019_%28crop%29.jpg",
  "tony-evers": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Tony_Evers_-_2022_%28a%29.jpg/440px-Tony_Evers_-_2022_%28a%29.jpg",
  "sarah-huckabee-sanders": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Governor_Sarah_Huckabee_Sanders_2026.jpg/440px-Governor_Sarah_Huckabee_Sanders_2026.jpg",
  "donald-trump": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Official_Presidential_Portrait_of_President_Donald_J._Trump_%282025%29_%28cropped%29%282%29.jpg/440px-Official_Presidential_Portrait_of_President_Donald_J._Trump_%282025%29_%28cropped%29%282%29.jpg",
  "kamala-harris": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Kamala_Harris_Vice_Presidential_Portrait.jpg/440px-Kamala_Harris_Vice_Presidential_Portrait.jpg",
  "jd-vance": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/March_2026_Official_Vice_Presidential_Portrait_of_JD_Vance_%28head-and-shoulders_cropped%29.jpg/440px-March_2026_Official_Vice_Presidential_Portrait_of_JD_Vance_%28head-and-shoulders_cropped%29.jpg",
  "kathy-hochul": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Kathy_Hochul_March_2024.jpg/440px-Kathy_Hochul_March_2024.jpg",
  "wes-moore": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Wes_Moore_Official_Governor_Portrait.jpg/440px-Wes_Moore_Official_Governor_Portrait.jpg",
  "hakeem-jeffries": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Rep-Hakeem-Jeffries-Official-Portrait_%28cropped%29.jpg/440px-Rep-Hakeem-Jeffries-Official-Portrait_%28cropped%29.jpg",
  "joe-biden": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Joe_Biden_presidential_portrait.jpg/440px-Joe_Biden_presidential_portrait.jpg",
  "mitch-mcconnell": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Mitch_McConnell_2016_official_photo_%281%29_%28cropped%29.jpg/440px-Mitch_McConnell_2016_official_photo_%281%29_%28cropped%29.jpg",
  "barack-obama": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/President_Barack_Obama.jpg/440px-President_Barack_Obama.jpg",
  "mike-johnson": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Speaker_Mike_Johnson_Official_Portrait_%28cropped%29%28b%29.jpg/440px-Speaker_Mike_Johnson_Official_Portrait_%28cropped%29%28b%29.jpg",
  "chuck-schumer": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Chuck_Schumer_official_photo.jpg/440px-Chuck_Schumer_official_photo.jpg",
  "bernie-sanders": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Bernie_Sanders_February_2026_%28cropped%29.jpg/440px-Bernie_Sanders_February_2026_%28cropped%29.jpg",
  "elizabeth-warren": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Elizabeth_Warren_by_Gage_Skidmore.jpg/440px-Elizabeth_Warren_by_Gage_Skidmore.jpg",
  "aoc": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Alexandria_Ocasio-Cortez_Official_Portrait.jpg/440px-Alexandria_Ocasio-Cortez_Official_Portrait.jpg",
  "tim-scott": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Tim_Scott_official_portrait.jpg/440px-Tim_Scott_official_portrait.jpg",
  "chris-murphy": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Chris_Murphy_in_Paris%2C_France_2025_%28cropped%29.jpg/440px-Chris_Murphy_in_Paris%2C_France_2025_%28cropped%29.jpg",
  "marco-rubio": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Official_portrait_of_Secretary_Marco_Rubio_%28cropped%29%282%29.jpg/440px-Official_portrait_of_Secretary_Marco_Rubio_%28cropped%29%282%29.jpg",
  "nikki-haley": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Nikki_Haley_official_photo.jpg/440px-Nikki_Haley_official_photo.jpg",
  "keir-starmer": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Prime_Minister_Keir_Starmer_Portrait_%28cropped%29.jpg/440px-Prime_Minister_Keir_Starmer_Portrait_%28cropped%29.jpg",
  "amy-klobuchar": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Amy_Klobuchar%2C_official_portrait%2C_113th_Congress.jpg/440px-Amy_Klobuchar%2C_official_portrait%2C_113th_Congress.jpg",
  "vivek-ramaswamy": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Vivek_Ramaswamy_%2855241367373%29_%28cropped%29.jpg/440px-Vivek_Ramaswamy_%2855241367373%29_%28cropped%29.jpg",
  "rfk-jr": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Robert_F._Kennedy_Jr.%2C_official_portrait_%282025%29_%28cropped_3-4%29_%28b%29.jpg/440px-Robert_F._Kennedy_Jr.%2C_official_portrait_%282025%29_%28cropped_3-4%29_%28b%29.jpg",
  "zohran-mamdani": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Zohran_Mamdani_05.25.25_%28b%29_%28cropped%29.jpg/440px-Zohran_Mamdani_05.25.25_%28b%29_%28cropped%29.jpg",
  "benjamin-netanyahu": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Benjamin_Netanyahu%2C_February_2023.jpg/440px-Benjamin_Netanyahu%2C_February_2023.jpg",
  "vladimir-putin": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%9F%D1%83%D1%82%D0%B8%D0%BD_%2808-03-2024%29_%28cropped%29_%28higher_res%29_2.jpg/440px-%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%9F%D1%83%D1%82%D0%B8%D0%BD_%2808-03-2024%29_%28cropped%29_%28higher_res%29_2.jpg",
  "xi-jinping": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Xi_Jinping_meets_Putin_May_2026.jpg/440px-Xi_Jinping_meets_Putin_May_2026.jpg",
  "mark-carney": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/2025-11-14_InaugurationREM_Deux-Montagnes_Mark_Carney.jpg/440px-2025-11-14_InaugurationREM_Deux-Montagnes_Mark_Carney.jpg",
  "volodymyr-zelenskyy": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Volodymyr_Zelensky_2022_official_portrait_%28cropped%29.jpg/440px-Volodymyr_Zelensky_2022_official_portrait_%28cropped%29.jpg",
  "nigel-farage": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Official_portrait_of_Nigel_Farage_MP_%283x4_cropped%29.jpg/440px-Official_portrait_of_Nigel_Farage_MP_%283x4_cropped%29.jpg",
  "justin-trudeau": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Prime_Minister_Trudeau%27s_message_on_Christmas_2023_%280m29s%29_%28cropped%29.jpg/440px-Prime_Minister_Trudeau%27s_message_on_Christmas_2023_%280m29s%29_%28cropped%29.jpg",
};

export function photoForSlug(slug: string): string | null {
  return POLITICIAN_PHOTOS[slug] ?? null;
}

/** Initials for monogram fallback (e.g. "Jon Ossoff" → "JO"). */
export function monogram(name: string): string {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return "?";
  if (parts.length === 1) return parts[0]!.slice(0, 2).toUpperCase();
  return (parts[0]![0]! + parts[parts.length - 1]![0]!).toUpperCase();
}
